#! /bin/bash

# This script is used to create a default setup for a new
# c++ project, includes a dummy makefile for g++11.

echo -n "Enter Project Name: "
read pname
mkdir $PWD/$pname
mkdir $PWD/$pname/src
touch $PWD/$pname/Makefile
touch $PWD/$pname/src/main.cpp

$date = date +"%T %d/%m/%y"

echo "# Wich compiler to use
CXX=g++

# Wich options to compile with
# -std=c++11 use g++11 compiler, -c compile into an object file, -Wall turn on all warnings.
CXXFLAGS=-std=c++11 -c -Wall

# Linking libraries
LDFLAGS = 

SOURCES = src/main.cpp
OBJECTS = \$(SOURCES:.cpp=.o)

EXECUTABLE = main

all: \$(SOURCES) \$(EXECUTABLE)

\$(EXECUTABLE): \$(OBJECTS)
\t\$(CXX) \$(OBJECTS) \$(LDFLAGS) -o \$@

.cpp.o:
\t\$(CXX) \$(CXXFLAGS) \$< -o \$@" > $PWD/$pname/Makefile

echo "// Description: New project
// Author: Jonas Knarbakk ($date)

#include <cstdio>

int main( int argc, char ** argv ){

    puts(\"Hello World!\");
    return 0;

}" > $PWD/$pname/src/main.cpp
